# We need Python 3 for the tests, but, if we add Python 3 as a language, it will be
# installed in a virtualenv where bin/python points to Python 3.
# Then "python clang-format-diff" is spawned and this ends up using Python 2 instead
# of the required Python 2.7.
language: generic

os:
  - linux
  - osx

# On Ubuntu:
# - coreutils is for readlink.
# - Python 2.7 for clang-format-diff.
# - Python 3.4 for the actual tests.
before_install:
  - >
    if [ "$TRAVIS_OS_NAME" = osx ]; then \
        echo XXX\ "MARKER: 1" && \
        brew update && \
        echo XXX\ "MARKER: 2" && \
        echo brew upgrade python && \
        echo XXX\ "MARKER: 3" && \
        brew list &&
        echo XXX\ "MARKER: 3.1" && \
        brew uninstall oclint && \
        echo XXX\ "MARKER: 3.2" && \
        brew install gcc && \
        echo XXX\ "MARKER: 4" && \
        brew install clang-format && \
        echo XXX\ "MARKER: 5" && \
        brew install shellcheck && \
        echo XXX\ "MARKER: 6" && \
        which /usr/local/bin/clang-format || \
            ( \
                echo "clang-format not installed";
                false \
            ) && \
        echo XXX\ "MARKER: 7" && \
        which /usr/local/bin/shellcheck || \
            ( \
                echo "shellcheck not installed";
                false \
            ) && \
        echo XXX\ "MARKER: 8" && \
        sudo pip3 install pylint; \
    else \
        sudo apt-get update && \
        sudo apt-get install -y \
            clang-format-3.8 \
            coreutils \
            python2.7 \
            python3-pip \
            python3.5 \
            shellcheck \
            && \
        sudo pip3 install virtualenv && \
        virtualenv --python=python3.5 venv-for-travis && \
        . ./venv-for-travis/bin/activate && \
        pip install pylint && \
        deactivate; \
    fi

script:
  - ./run-checks
